name: Deploy Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: dotnet publish src/BlazorProject/BlazorProject.csproj -c Release -o release --nologo
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        # Build directory to deploy
        build_dir: release/wwwroot
        # If enabled, nothing will be pushed
        dry_run: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
